.then((contentsAll) => contentsAll.split("\n"))
  // .then(isAVoid)
  // .then((lines) => isAInclude(lines, "-->"))
  // .then((lines) => isANumber(lines))
  // .then(removeSpecialCaracteres(symbols))
  // .then((array) => array.join(" "))
  // .then((words) => words.split(" "))
  // .then(isAVoid)
  // .then((lines) => isANumber(lines))
  // .then(countingWords)
  // .then(orderBy("qtd", "desc"))